name = "SlateBench"
uuid = "34dae1dd-9e9d-4399-81aa-9d72c5d23232"
version = "0.1.0"
authors = ["Kahli Burke <kahli@kahliburke.com>"]

[deps]
SlateExtensionsBase = "bc31d39e-4442-48fa-b9ae-1bd99fed63f7"

[compat]
SlateExtensionsBase = "0.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
